In [12]:
import numpy as np
arr1 = ([1,2,3],[4,0,1],[10,11,0])

In [13]:
arr = np.array(arr1)
arr

array([[ 1,  2,  3],
       [ 4,  0,  1],
       [10, 11,  0]])

In [14]:
arr.argmax(axis = 1)

array([2, 0, 1])

In [15]:
arr.cumsum()

array([ 1,  3,  6, 10, 10, 11, 21, 32, 32])

In [47]:
arr2 = np.random.randint(low=2,high=10,size=(3,3))
arr3 = np.random.randint(low=5,high=8,size=(3,3),dtype = np.int32)

In [62]:
print(arr2)
arr4 = arr2.astype(np.float64)
arr4

[[8 7 9]
 [6 5 3]
 [9 6 8]]


array([[8., 7., 9.],
       [6., 5., 3.],
       [9., 6., 8.]])

In [50]:
print(arr3.dtype)
print(arr3)
print(arr3[1,1])

int32
[[6 7 5]
 [6 6 6]
 [7 6 7]]
6


In [60]:
np.vstack((arr2,arr3))

array([[8, 7, 9],
       [6, 5, 3],
       [9, 6, 8],
       [6, 7, 5],
       [6, 6, 6],
       [7, 6, 7]])

In [44]:
np.hstack((arr2,arr3))

array([[2, 2, 8, 6, 6, 5],
       [2, 7, 9, 6, 7, 6],
       [9, 3, 5, 6, 6, 5]])

In [65]:
arr4

array([[8., 7., 9.],
       [6., 5., 3.],
       [9., 6., 8.]])