### **Assignment: Introduction to Linear Algebra and NumPy**

#### **Objective:**
This assignment will help you build a solid understanding of basic Linear Algebra concepts using Python and the NumPy library. You'll learn to create and manipulate arrays, perform mathematical operations, and explore properties and methods of arrays.


### **Working with NumPy**

NumPy is a powerful Python library for numerical computations, which allows easy manipulation of arrays and matrices.

**Task 1:** 
- Import the `numpy` library and check its version.


In [ ]:
import numpy as np
print(np.__version__)

2.1.1



### **Creating a NumPy Array:**

NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

**Task 2:**
- Create a 1D NumPy array from a Python list of numbers: `[1, 2, 3, 4, 5]`.
- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
- Generate an array of 10 evenly spaced values between 0 and 5.

In [131]:
# Solution Here
arr = [1,2,3,4,5]
list_of_numbers = np.array(arr)
list_of_numbers

array([1, 2, 3, 4, 5])

In [132]:
arr1 = np.random.randint(low=1, high= 9,size=(3,3))
arr2 = np.random.randint(low=1, high= 9,size=(3,3))

d_arr = np.array((arr1,arr2))
d_arr

array([[[4, 4, 2],
        [5, 7, 6],
        [8, 3, 8]],

       [[3, 6, 5],
        [1, 8, 5],
        [1, 5, 7]]])

In [133]:
print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### **Indexing and Slicing Arrays:**

Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**
- Access the element in the second row, third column of the 2D array you created above.
- Slice the first two rows and the first two columns from the same array.
- Modify the value in the last row and first column to 100.


In [134]:
# Solution Here
print(d_arr)

el1 = d_arr[0][1][2]

el2 = d_arr[1][1][2]

print(el1)
print(el2)

[[[4 4 2]
  [5 7 6]
  [8 3 8]]

 [[3 6 5]
  [1 8 5]
  [1 5 7]]]
6
5


In [135]:
print(d_arr)
print("\n")
sliced_arr = d_arr[:,:2,:2]
print(sliced_arr)

[[[4 4 2]
  [5 7 6]
  [8 3 8]]

 [[3 6 5]
  [1 8 5]
  [1 5 7]]]


[[[4 4]
  [5 7]]

 [[3 6]
  [1 8]]]


In [136]:
print(d_arr)
print("\n")
new_arr = d_arr.copy()
new_arr2 = new_arr[0][0][:] = [100,100,100]

new_arr[:, 0, 0] = 100
print(new_arr)

[[[4 4 2]
  [5 7 6]
  [8 3 8]]

 [[3 6 5]
  [1 8 5]
  [1 5 7]]]


[[[100 100 100]
  [  5   7   6]
  [  8   3   8]]

 [[100   6   5]
  [  1   8   5]
  [  1   5   7]]]


### **Properties and Methods of NumPy Arrays**

NumPy arrays have several useful properties and methods.

**Task 4:**
- Find the shape, size, and data type of the 2D array.
- Change the 1D array into a 2D array of shape (5,1).
- Flatten a multi-dimensional array back into a 1D array.

In [141]:
# Solution Here
print(f"size of arr1 is {arr1.size}")
print(f"shape of arr1 is {arr1.shape}")
print(f"shape of arr1 is {arr1.dtype}")

size of arr1 is 9
shape of arr1 is (3, 3)
shape of arr1 is int64


In [ ]:
# re_shaped_arr = arr.reshape(5,1)

a = [1,2,3,4,5,6]
new_arr = np.array(a)
new_arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [161]:
print(d_arr)

flatten_arr = d_arr.flatten()
print("\n")
flatten_arr

[[[4 4 2]
  [5 7 6]
  [8 3 8]]

 [[3 6 5]
  [1 8 5]
  [1 5 7]]]




array([4, 4, 2, 5, 7, 6, 8, 3, 8, 3, 6, 5, 1, 8, 5, 1, 5, 7])

### **Operations on NumPy Arrays**

Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**
- Add 5 to every element in the 1D array.
- Multiply the 2D array by 3.
- Perform matrix multiplication between the following two arrays:  
    ```python
    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

In [36]:
# Solution Here
print(arr1)
print("\n")
print(arr1 + 5)

[[8 6 3]
 [8 5 3]
 [5 2 8]]


[[13 11  8]
 [13 10  8]
 [10  7 13]]


In [39]:
print(arr2)
print("\n")
print(arr2 * 3)

[[6 4 3]
 [3 1 8]
 [4 1 7]]


[[18 12  9]
 [ 9  3 24]
 [12  3 21]]


In [48]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
mul_arr = A * B
print(A)
print("\n")
print(B)
print("\n")
print(mul_arr)

[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 5 12]
 [21 32]]


### **Understanding Broadcasting**

Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.

**Task 6:**
- Create a 3x3 matrix of ones and a 1D array of length 3.
- Add the 1D array to each row of the matrix using broadcasting.

In [ ]:
# Solution Here
